
import React, { useState } from "react";
import { motion } from "framer-motion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";
import FileUpload from "@/components/FileUpload";
import DocumentSummary from "@/components/DocumentSummary";
import QuizGenerator from "@/components/QuizGenerator";
import QuizInterface from "@/components/QuizInterface";

function App() {
  const [activeDocument, setActiveDocument] = useState(null);
  const [documentSummary, setDocumentSummary] = useState("");
  const [activeQuiz, setActiveQuiz] = useState(null);
  const [activeTab, setActiveTab] = useState("upload");

  const handleFileUpload = (file) => {
    setActiveDocument(file);
    
    // Simulate AI processing and generate a summary
    setTimeout(() => {
      const summary = generateMockSummary(file.name);
      setDocumentSummary(summary);
      setActiveTab("summary");
    }, 1000);
  };

  const handleStartQuiz = (quiz) => {
    setActiveQuiz(quiz);
    setActiveTab("quiz");
  };

  const handleFinishQuiz = () => {
    setActiveQuiz(null);
    setActiveTab("summary");
  };

  const handleRestartQuiz = () => {
    setActiveTab("generate");
  };

  const generateMockSummary = (fileName) => {
    // This is a mock summary that would normally be generated by an AI
    return `Ce document traite des méthodes d'apprentissage efficaces pour les étudiants. Il présente plusieurs techniques basées sur les recherches en sciences cognitives.

Les points clés abordés sont:

1. La répétition espacée: Cette technique consiste à réviser le matériel à des intervalles croissants, ce qui renforce la mémorisation à long terme. Le document explique comment planifier ces sessions de révision pour maximiser la rétention.

2. La pratique de récupération: Au lieu de simplement relire les notes, le document recommande de se tester régulièrement. Cette méthode active la mémoire et renforce les connexions neuronales associées à l'information.

3. L'apprentissage par association: Le document détaille comment relier de nouvelles informations à des connaissances existantes pour faciliter leur mémorisation.

4. La gestion du temps: Une section importante est consacrée aux techniques de planification et d'organisation des sessions d'étude, avec des recommandations sur la durée optimale et les pauses.

5. Les techniques de concentration: Le document aborde les méthodes pour minimiser les distractions et maintenir un niveau élevé de concentration pendant les sessions d'étude.

En conclusion, le document souligne l'importance d'adopter une approche scientifique de l'apprentissage, en utilisant des méthodes validées par la recherche plutôt que de se fier à des intuitions qui peuvent être contre-productives.`;
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 container py-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto"
        >
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold tracking-tight mb-2">
              Révision Intelligente avec l'IA
            </h1>
            <p className="text-muted-foreground">
              Téléchargez vos documents, obtenez des résumés et testez vos connaissances avec des quiz personnalisés
            </p>
          </div>
          
          {activeDocument ? (
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid grid-cols-3 mb-8">
                <TabsTrigger value="upload">Document</TabsTrigger>
                <TabsTrigger value="summary">Résumé</TabsTrigger>
                <TabsTrigger value="generate" disabled={!documentSummary}>
                  Quiz
                </TabsTrigger>
              </TabsList>
              
              <TabsContent value="upload" className="mt-0">
                <FileUpload onFileUpload={handleFileUpload} />
              </TabsContent>
              
              <TabsContent value="summary" className="mt-0">
                {documentSummary && (
                  <DocumentSummary 
                    document={activeDocument} 
                    summary={documentSummary} 
                  />
                )}
              </TabsContent>
              
              <TabsContent value="generate" className="mt-0">
                {!activeQuiz ? (
                  <QuizGenerator 
                    document={activeDocument} 
                    onStartQuiz={handleStartQuiz} 
                  />
                ) : (
                  <QuizInterface 
                    quiz={activeQuiz} 
                    onFinish={handleFinishQuiz}
                    onRestart={handleRestartQuiz}
                  />
                )}
              </TabsContent>
              
              <TabsContent value="quiz" className="mt-0">
                {activeQuiz && (
                  <QuizInterface 
                    quiz={activeQuiz} 
                    onFinish={handleFinishQuiz}
                    onRestart={handleRestartQuiz}
                  />
                )}
              </TabsContent>
            </Tabs>
          ) : (
            <div className="space-y-8">
              <div className="gradient-bg text-white rounded-lg p-8 text-center">
                <h2 className="text-2xl font-bold mb-4">
                  Améliorez votre apprentissage avec l'IA
                </h2>
                <p className="mb-6">
                  Téléchargez vos documents de cours et laissez notre IA vous aider à mieux comprendre et mémoriser le contenu
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
                  <div className="glass-card rounded-lg p-4 text-center">
                    <div className="bg-white/20 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-3">
                      <img  alt="Upload icon" className="w-6 h-6" src="https://images.unsplash.com/photo-1595872018818-97555653a011" />
                    </div>
                    <h3 className="font-medium mb-2">Téléchargez</h3>
                    <p className="text-sm opacity-80">Importez vos documents de cours (PDF, DOC, TXT)</p>
                  </div>
                  <div className="glass-card rounded-lg p-4 text-center">
                    <div className="bg-white/20 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-3">
                      <img  alt="AI icon" className="w-6 h-6" src="https://images.unsplash.com/photo-1677442136019-21780ecad995" />
                    </div>
                    <h3 className="font-medium mb-2">Résumez</h3>
                    <p className="text-sm opacity-80">Obtenez un résumé intelligent généré par IA</p>
                  </div>
                  <div className="glass-card rounded-lg p-4 text-center">
                    <div className="bg-white/20 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-3">
                      <img  alt="Quiz icon" className="w-6 h-6" src="https://images.unsplash.com/photo-1633613286848-e6f43bbafb8d" />
                    </div>
                    <h3 className="font-medium mb-2">Testez</h3>
                    <p className="text-sm opacity-80">Créez des quiz personnalisés pour tester vos connaissances</p>
                  </div>
                </div>
              </div>
              
              <FileUpload onFileUpload={handleFileUpload} />
            </div>
          )}
        </motion.div>
      </main>
      
      <footer className="border-t py-6 md:py-0">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-4 md:h-16">
          <p className="text-sm text-muted-foreground">
            © 2025 Talento. Tous droits réservés.
          </p>
          <div className="flex items-center gap-4">
            <a href="#" className="text-sm text-muted-foreground hover:text-foreground">
              Confidentialité
            </a>
            <a href="#" className="text-sm text-muted-foreground hover:text-foreground">
              Conditions
            </a>
            <a href="#" className="text-sm text-muted-foreground hover:text-foreground">
              Contact
            </a>
          </div>
        </div>
      </footer>
      
      <Toaster />
    </div>
  );
}

export default App;
